### ISSUE TITLE
自定义loading图片不生效

### ISSUE THREAD

**Issue by vimcaw** [Troy-Yang/hexo-lazyload-image#2]
图片放在主题下的`source/image/loading_mini.gif`, _config.yml:
```yaml
# lazyload image
lazyload:
  enable: true
  onlypost: true
  loadingImg: './image/loading_mini.gif'
```
结果重新生成后还是默认的loading图片，是路径的问题吗？我换成`./source/image/loading_mini.gif`后还是不生效。
