### ISSUE TITLE
几个功能增强建议

### ISSUE THREAD

**Issue by appotry** [Troy-Yang/hexo-lazyload-image#39]
## 1. 支持div 的style background

在html文件中的
```html
<div class="ajustedBackground"  style="background-image: url('loading-image');"><div>
```

这个插件实现了这个功能，[hexo-filter-lqip](https://github.com/hexojs/hexo-filter-lqip)，可以参考实现

## 2. 支持在css文件中的图片

```css
div.waline {
    background: url("/medias_webp/loading.svg") 100% 100% no-repeat; /* Placeholder image */
}
```

## 3 支持获取占位图片的宽高

> 没有宽高，可用，但存在一些问题
> - 没有宽高，一些性能测试工具会报错
> - lazyload显示前后文章宽高会跳动

### 3.1 本地图片

直接获取图片宽高

#### 方法1  可以缓存到本地目录来获取宽高

这个插件实现了这个功能 
[hexo-native-lazy-load](https://github.com/fengkx/hexo-native-lazy-load/blob/master/lib/replace.js)

#### 方法2 链接路径映射到目录路径

如果是github仓库的图片
本地clone仓库目录和网页链接之间做一个映射，那么就不需要再次下载图片来获取宽高了
