### ISSUE TITLE
onlypost 为true时 不工作

### ISSUE THREAD

**Issue by nanbowanya** [Troy-Yang/hexo-lazyload-image#47]
我使用的是icarus主题，hexo-lazyload-image用的是最新版，但依然会存在点击大图只显示加载。使用中#1 的方法均尝试无效，请问是否有具体解决办法。

**Comment by Troy-Yang** [comment]
我在本地试了最新的icarus 主题，只需要在_config.yml配置文件里，加上插件配置就可以了，默认页面加载时可以懒加载，点击图片也能正常显示图片。并不需要像https://github.com/Troy-Yang/hexo-lazyload-image/issues/1 这里的手动改动，实际上，这个改动已经集成进这个插件了
```
theme: icarus
deploy:
  type: ''
lazyload:
  enable: true
  onlypost: false # optional
  loadingImg: # optional eg ./images/loading.gif
  isSPA: false # optional
  preloadRatio: 3 # optional, default is 1
```

你能提供一个在线的地址吗
