### ISSUE TITLE
关于lazyload图片占位大小的自适应的一种实现

### ISSUE THREAD

**Issue by appotry** [Troy-Yang/hexo-lazyload-image#58]
```css
#artDetail img[lazyload]:not(.loaded) {
  max-width: 100%;
  width: 100%; // 或 auto（根据设计需求调整）
  height: auto !important; // 强制高度由宽高比计算
}
```

```JavaScript
document.querySelectorAll('#artDetail img[lazyload]').forEach(img => {
  const width = img.getAttribute('width');
  const height = img.getAttribute('height');
  if (width && height) {
    // 仅设置宽高比 + 宽度自适应（高度自动计算）
    img.style.aspectRatio = `${width}/${height}`;
    img.style.width = '100%'; // 或 max-width: 100%（通过 CSS 控制）
  }
});
```

这个可加可不加，加上体验更好一些
